---
resources:
- name: websec
  type: git
  source:
    uri: {{github-repository}}
    branch: master
    private_key: {{github-private-key}}

- name: websec-artifacts
  type: s3
  source:
    bucket: {{bucket}}
    regexp: releases/websec-(.*).jar
    access_key_id: {{access-key-id}}
    secret_access_key: {{secret-access-key}}
    endpoint: {{endpoint}}
    skip_ssl_verification: true
    disable_ssl: true

- name: version
  type: semver
  source:
    bucket: {{bucket}}
    key: websec/version
    access_key_id: {{access-key-id}}
    secret_access_key: {{secret-access-key}}
    endpoint: {{endpoint}}
    skip_ssl_verification: true
    disable_ssl: true

- name: dev-deployment
  type: cf
  source:
    api: {{cf-api-url}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-org}}
    space: dev
    skip_cert_check:  true

jobs:
- name: build
  plan:
  - get: websec
    trigger: true
  - get: version
    params: {bump: patch}
  - task: build
    file: websec/ci/build.yml
  - put: websec-artifacts
    params:
      file: build-output/websec-*.jar
  - put: version
    params:
      file: version/number

- name: deploy-dev
  plan:
  - get: websec
    passed: [build]
  - get: websec-artifacts
    trigger: false
    passed: [build]
  - put: dev-deployment
    params:
      manifest: websec/manifest-dev.yml
      path: websec-artifacts/websec-*.jar